### ISSUE TITLE
use --expand ?

### ISSUE THREAD

**Issue by wivaku** [blacklabelops/letsencrypt#3]
Is it possible to add default / make it configurable: `--expand`:

> tells Certbot to update an existing certificate with a new certificate that contains all of the old domains and one or more additional new domains. With the --expand option, use the -d option to specify all existing domains and one or more new domains

https://certbot.eff.org/docs/using.html#re-creating-and-updating-existing-certificates

**Comment by blacklabelops** [comment]
You can now add all parameters to any command.

**Comment by wivaku** [comment]
thanks Steffen!
